-- --------------------------------------------------------
-- Host:                         192.168.1.197
-- Server version:               10.3.29-MariaDB-0+deb10u1 - Debian 10
-- Server OS:                    debian-linux-gnu
-- HeidiSQL Version:             11.3.0.6295
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for db_oi
CREATE DATABASE IF NOT EXISTS `db_oi` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `db_oi`;

-- Dumping structure for table db_oi.OI_ALARM_CONFIGURATION
CREATE TABLE IF NOT EXISTS `OI_ALARM_CONFIGURATION` (
  `ID_ALARM_CONFIG` int(11) NOT NULL,
  `ID_ALARM` int(11) DEFAULT NULL,
  `ID_VARIABLE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_ALARM_CONFIG`),
  KEY `FK_OI_ALARM_REFERENCE_OI_PROCE` (`ID_VARIABLE`),
  CONSTRAINT `FK_OI_ALARM_REFERENCE_OI_PROCE` FOREIGN KEY (`ID_VARIABLE`) REFERENCES `OI_PROCESS_VARIABLE` (`ID_VARIABLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_ALARM_CONFIGURATION: ~0 rows (approximately)
DELETE FROM `OI_ALARM_CONFIGURATION`;
/*!40000 ALTER TABLE `OI_ALARM_CONFIGURATION` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_ALARM_CONFIGURATION` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_ALARM_GROUP
CREATE TABLE IF NOT EXISTS `OI_ALARM_GROUP` (
  `ID_ALARM_GROUP` int(11) NOT NULL,
  `GROUPNAME` varchar(100) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID_ALARM_GROUP`),
  UNIQUE KEY `INDEX_1` (`ID_ALARM_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_ALARM_GROUP: ~0 rows (approximately)
DELETE FROM `OI_ALARM_GROUP`;
/*!40000 ALTER TABLE `OI_ALARM_GROUP` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_ALARM_GROUP` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_COUNTER
CREATE TABLE IF NOT EXISTS `OI_COUNTER` (
  `ID_COUNT` int(11) NOT NULL,
  `ID_FUNCTION` int(11) DEFAULT NULL,
  `INPUTVARIABLE` int(11) DEFAULT NULL,
  `OUTPUTVARIABLE` int(11) DEFAULT NULL,
  `COUNTNAME` varchar(200) DEFAULT NULL,
  `COUNTTYPE` varchar(20) DEFAULT NULL,
  `ACCUMULATOR` int(11) DEFAULT NULL,
  `PRESET` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_COUNT`),
  KEY `FK_OI_COUNT_REFERENCE_OI_PROCE` (`INPUTVARIABLE`),
  KEY `FK_OI_COUNT_REFERENCE_OI_FUNCT` (`ID_FUNCTION`),
  CONSTRAINT `FK_OI_COUNT_REFERENCE_OI_FUNCT` FOREIGN KEY (`ID_FUNCTION`) REFERENCES `OI_FUNCTION_LIST` (`ID_FUNCTION`),
  CONSTRAINT `FK_OI_COUNT_REFERENCE_OI_PROCE` FOREIGN KEY (`INPUTVARIABLE`) REFERENCES `OI_PROCESS_VARIABLE` (`ID_VARIABLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_COUNTER: ~0 rows (approximately)
DELETE FROM `OI_COUNTER`;
/*!40000 ALTER TABLE `OI_COUNTER` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_COUNTER` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_DRIVER
CREATE TABLE IF NOT EXISTS `OI_DRIVER` (
  `ID_DRIVER` int(11) NOT NULL,
  `DRIVERNAME` varchar(50) DEFAULT NULL,
  `ISRUNNING` tinyint(1) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID_DRIVER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_DRIVER: ~0 rows (approximately)
DELETE FROM `OI_DRIVER`;
/*!40000 ALTER TABLE `OI_DRIVER` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_DRIVER` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_DRIVER_CONFIGURATION
CREATE TABLE IF NOT EXISTS `OI_DRIVER_CONFIGURATION` (
  `ID_DRIVER_CONFIG` int(11) NOT NULL,
  `ID_DRIVER` int(11) DEFAULT NULL,
  `CONFIGNAME` varchar(100) DEFAULT NULL,
  `VALUE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_DRIVER_CONFIG`),
  KEY `INDEX_1` (`ID_DRIVER_CONFIG`),
  KEY `FK_OI_DRIVE_CONFIGDRI_OI_DRIVE` (`ID_DRIVER`),
  CONSTRAINT `FK_OI_DRIVE_CONFIGDRI_OI_DRIVE` FOREIGN KEY (`ID_DRIVER`) REFERENCES `OI_DRIVER` (`ID_DRIVER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_DRIVER_CONFIGURATION: ~0 rows (approximately)
DELETE FROM `OI_DRIVER_CONFIGURATION`;
/*!40000 ALTER TABLE `OI_DRIVER_CONFIGURATION` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_DRIVER_CONFIGURATION` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_FRAME_LIST
CREATE TABLE IF NOT EXISTS `OI_FRAME_LIST` (
  `ID_FRAME` int(11) NOT NULL,
  `FRAMENAME` varchar(200) DEFAULT NULL,
  `FIXED` tinyint(1) DEFAULT NULL,
  `TOP` int(11) DEFAULT NULL,
  `BOTTOM` int(11) DEFAULT NULL,
  `WIDTH` int(11) DEFAULT NULL,
  `HEIGHT` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_FRAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_FRAME_LIST: ~0 rows (approximately)
DELETE FROM `OI_FRAME_LIST`;
/*!40000 ALTER TABLE `OI_FRAME_LIST` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_FRAME_LIST` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_FUNCTION_CATEGORY
CREATE TABLE IF NOT EXISTS `OI_FUNCTION_CATEGORY` (
  `ID_FUNC_CATEGORY` int(11) NOT NULL,
  `CATEGORYNAME` varchar(20) DEFAULT NULL,
  `DESCRIPTION` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_FUNC_CATEGORY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_FUNCTION_CATEGORY: ~1 rows (approximately)
DELETE FROM `OI_FUNCTION_CATEGORY`;
/*!40000 ALTER TABLE `OI_FUNCTION_CATEGORY` DISABLE KEYS */;
INSERT INTO `OI_FUNCTION_CATEGORY` (`ID_FUNC_CATEGORY`, `CATEGORYNAME`, `DESCRIPTION`) VALUES
	(1, '1', '1');
/*!40000 ALTER TABLE `OI_FUNCTION_CATEGORY` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_FUNCTION_DETAILCONFIG
CREATE TABLE IF NOT EXISTS `OI_FUNCTION_DETAILCONFIG` (
  `ID_FUNCTION_CONFIG` int(11) NOT NULL,
  `ID_FUNC_CATEGORY` int(11) DEFAULT NULL,
  `CONFIGNAME` varchar(100) DEFAULT NULL,
  `VALUE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_FUNCTION_CONFIG`),
  KEY `FK_OI_FUNCT_REFERENCE_OI_FUNCT` (`ID_FUNC_CATEGORY`),
  CONSTRAINT `FK_OI_FUNCT_REFERENCE_OI_FUNCT` FOREIGN KEY (`ID_FUNC_CATEGORY`) REFERENCES `OI_FUNCTION_CATEGORY` (`ID_FUNC_CATEGORY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_FUNCTION_DETAILCONFIG: ~0 rows (approximately)
DELETE FROM `OI_FUNCTION_DETAILCONFIG`;
/*!40000 ALTER TABLE `OI_FUNCTION_DETAILCONFIG` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_FUNCTION_DETAILCONFIG` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_FUNCTION_LIST
CREATE TABLE IF NOT EXISTS `OI_FUNCTION_LIST` (
  `ID_FUNCTION` int(11) NOT NULL,
  `ID_FUNC_CATEGORY` int(11) DEFAULT NULL,
  `FUNCTIONNAME` varchar(100) DEFAULT NULL,
  `DESCRIPTION` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_FUNCTION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_FUNCTION_LIST: ~1 rows (approximately)
DELETE FROM `OI_FUNCTION_LIST`;
/*!40000 ALTER TABLE `OI_FUNCTION_LIST` DISABLE KEYS */;
INSERT INTO `OI_FUNCTION_LIST` (`ID_FUNCTION`, `ID_FUNC_CATEGORY`, `FUNCTIONNAME`, `DESCRIPTION`) VALUES
	(1, 1, 'ss', 'xx');
/*!40000 ALTER TABLE `OI_FUNCTION_LIST` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_HISTORIAN
CREATE TABLE IF NOT EXISTS `OI_HISTORIAN` (
  `ID_HISTORIAN` int(11) NOT NULL,
  `HISTORIANNAME` varchar(100) DEFAULT NULL,
  `HISTORIANTYPE` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID_HISTORIAN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_HISTORIAN: ~0 rows (approximately)
DELETE FROM `OI_HISTORIAN`;
/*!40000 ALTER TABLE `OI_HISTORIAN` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_HISTORIAN` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_HISTORIAN_CONFIGURATION
CREATE TABLE IF NOT EXISTS `OI_HISTORIAN_CONFIGURATION` (
  `ID_HISTORIAN_CONFIG` int(11) NOT NULL,
  `ID_HISTORIAN` int(11) DEFAULT NULL,
  `ID_VARIABLE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_HISTORIAN_CONFIG`),
  KEY `FK_OI_HISTO_REFERENCE_OI_HISTO` (`ID_HISTORIAN`),
  KEY `FK_OI_HISTO_REFERENCE_OI_PROCE` (`ID_VARIABLE`),
  CONSTRAINT `FK_OI_HISTO_REFERENCE_OI_HISTO` FOREIGN KEY (`ID_HISTORIAN`) REFERENCES `OI_HISTORIAN` (`ID_HISTORIAN`),
  CONSTRAINT `FK_OI_HISTO_REFERENCE_OI_PROCE` FOREIGN KEY (`ID_VARIABLE`) REFERENCES `OI_PROCESS_VARIABLE` (`ID_VARIABLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_HISTORIAN_CONFIGURATION: ~0 rows (approximately)
DELETE FROM `OI_HISTORIAN_CONFIGURATION`;
/*!40000 ALTER TABLE `OI_HISTORIAN_CONFIGURATION` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_HISTORIAN_CONFIGURATION` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_LOGGER
CREATE TABLE IF NOT EXISTS `OI_LOGGER` (
  `ID_LOGGER` int(11) NOT NULL,
  `LOGGERNAME` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_LOGGER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_LOGGER: ~0 rows (approximately)
DELETE FROM `OI_LOGGER`;
/*!40000 ALTER TABLE `OI_LOGGER` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_LOGGER` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_LOGGER_CONFIGURATION
CREATE TABLE IF NOT EXISTS `OI_LOGGER_CONFIGURATION` (
  `ID_LOGGER_CONFIG` int(11) NOT NULL,
  `ID_LOGGER` int(11) DEFAULT NULL,
  `ID_VARIABLE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_LOGGER_CONFIG`),
  KEY `FK_OI_LOGGE_REFERENCE_OI_LOGGE` (`ID_LOGGER`),
  KEY `FK_OI_LOGGE_REFERENCE_OI_PROCE` (`ID_VARIABLE`),
  CONSTRAINT `FK_OI_LOGGE_REFERENCE_OI_LOGGE` FOREIGN KEY (`ID_LOGGER`) REFERENCES `OI_LOGGER` (`ID_LOGGER`),
  CONSTRAINT `FK_OI_LOGGE_REFERENCE_OI_PROCE` FOREIGN KEY (`ID_VARIABLE`) REFERENCES `OI_PROCESS_VARIABLE` (`ID_VARIABLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_LOGGER_CONFIGURATION: ~0 rows (approximately)
DELETE FROM `OI_LOGGER_CONFIGURATION`;
/*!40000 ALTER TABLE `OI_LOGGER_CONFIGURATION` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_LOGGER_CONFIGURATION` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_LOGIC
CREATE TABLE IF NOT EXISTS `OI_LOGIC` (
  `ID_LOGIC` int(11) NOT NULL,
  `OUTPUTVARIABLE` int(11) DEFAULT NULL,
  `LOGICNAME` varchar(200) DEFAULT NULL,
  `STATEMENTLOGIC` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_LOGIC`),
  KEY `FK_OI_LOGIC_REFERENCE_OI_PROCE` (`OUTPUTVARIABLE`),
  CONSTRAINT `FK_OI_LOGIC_REFERENCE_OI_PROCE` FOREIGN KEY (`OUTPUTVARIABLE`) REFERENCES `OI_PROCESS_VARIABLE` (`ID_VARIABLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_LOGIC: ~0 rows (approximately)
DELETE FROM `OI_LOGIC`;
/*!40000 ALTER TABLE `OI_LOGIC` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_LOGIC` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_LOGIN_SYSTEM
CREATE TABLE IF NOT EXISTS `OI_LOGIN_SYSTEM` (
  `ID_LOGIN` int(11) NOT NULL,
  `FIRSTNAME` varchar(25) DEFAULT NULL,
  `LASTNAME` varchar(25) DEFAULT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  `USERNAME` varchar(100) DEFAULT NULL,
  `LASTLOGIN` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_LOGIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Table untuk login session';

-- Dumping data for table db_oi.OI_LOGIN_SYSTEM: ~0 rows (approximately)
DELETE FROM `OI_LOGIN_SYSTEM`;
/*!40000 ALTER TABLE `OI_LOGIN_SYSTEM` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_LOGIN_SYSTEM` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_OBJECT_LIST
CREATE TABLE IF NOT EXISTS `OI_OBJECT_LIST` (
  `OBJECT_ID` int(11) NOT NULL,
  `ID_SCREEN` int(11) DEFAULT NULL,
  `ID_VARIABLE` int(11) DEFAULT NULL,
  `ID_FUNCTION` int(11) DEFAULT NULL,
  `OBJECTNAME` varchar(50) DEFAULT NULL,
  `OBJECTTYPE` varchar(50) DEFAULT NULL,
  `LAYER` int(11) DEFAULT NULL,
  `POS_X` int(11) DEFAULT NULL,
  `POS_Y` int(11) DEFAULT NULL,
  `WIDTH` int(11) DEFAULT NULL,
  `HEIGHT` int(11) DEFAULT NULL,
  `ROTATION` int(11) DEFAULT NULL,
  `IMAGE` varchar(20) DEFAULT NULL,
  `TEXT` varchar(100) DEFAULT NULL,
  `OBJECT_COLOR` varchar(10) DEFAULT NULL,
  `VISIBILITY` tinyint(1) DEFAULT NULL,
  `TRANSPARANCY` int(11) DEFAULT NULL,
  `FLASHING` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`OBJECT_ID`),
  UNIQUE KEY `INDEX_1` (`OBJECT_ID`),
  KEY `FK_OI_OBJEC_OBJTOFUNC_OI_FUNCT` (`ID_FUNCTION`),
  KEY `FK_OI_OBJEC_OBJTOSCRE_OI_SCREE` (`ID_SCREEN`),
  KEY `FK_OI_OBJEC_OBJTOVARI_OI_PROCE` (`ID_VARIABLE`),
  CONSTRAINT `FK_OI_OBJEC_OBJTOFUNC_OI_FUNCT` FOREIGN KEY (`ID_FUNCTION`) REFERENCES `OI_FUNCTION_LIST` (`ID_FUNCTION`),
  CONSTRAINT `FK_OI_OBJEC_OBJTOSCRE_OI_SCREE` FOREIGN KEY (`ID_SCREEN`) REFERENCES `OI_SCREEN_LIST` (`ID_SCREEN`),
  CONSTRAINT `FK_OI_OBJEC_OBJTOVARI_OI_PROCE` FOREIGN KEY (`ID_VARIABLE`) REFERENCES `OI_PROCESS_VARIABLE` (`ID_VARIABLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_OBJECT_LIST: ~0 rows (approximately)
DELETE FROM `OI_OBJECT_LIST`;
/*!40000 ALTER TABLE `OI_OBJECT_LIST` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_OBJECT_LIST` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_PROCESS_VARIABLE
CREATE TABLE IF NOT EXISTS `OI_PROCESS_VARIABLE` (
  `ID_VARIABLE` int(11) NOT NULL,
  `ID_DRIVER` int(11) DEFAULT NULL,
  `ID_VARIABLE_TYPE` int(11) DEFAULT NULL,
  `VARIABLENAME` varchar(100) DEFAULT NULL,
  `DEFAULTVALUE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID_VARIABLE`),
  KEY `FK_OI_PROCE_DRIVERPRO_OI_DRIVE` (`ID_DRIVER`),
  KEY `FK_OI_PROCE_REFERENCE_OI_VARIA` (`ID_VARIABLE_TYPE`),
  CONSTRAINT `FK_OI_PROCE_DRIVERPRO_OI_DRIVE` FOREIGN KEY (`ID_DRIVER`) REFERENCES `OI_DRIVER` (`ID_DRIVER`),
  CONSTRAINT `FK_OI_PROCE_REFERENCE_OI_VARIA` FOREIGN KEY (`ID_VARIABLE_TYPE`) REFERENCES `OI_VARIABLE_TYPE` (`ID_VARIABLE_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_PROCESS_VARIABLE: ~0 rows (approximately)
DELETE FROM `OI_PROCESS_VARIABLE`;
/*!40000 ALTER TABLE `OI_PROCESS_VARIABLE` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_PROCESS_VARIABLE` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_RENDUNDANCY_DETAIL
CREATE TABLE IF NOT EXISTS `OI_RENDUNDANCY_DETAIL` (
  `DETAIL_ID` int(11) NOT NULL,
  `RENDUNDANT_ID` int(11) NOT NULL,
  `CONFIGNAME` varchar(50) DEFAULT NULL,
  `VALUE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`DETAIL_ID`),
  KEY `FK_OI_RENDU_RENDUNDAN_OI_RENDU` (`RENDUNDANT_ID`),
  CONSTRAINT `FK_OI_RENDU_RENDUNDAN_OI_RENDU` FOREIGN KEY (`RENDUNDANT_ID`) REFERENCES `OI_RENDUNDANCY_STATE` (`RENDUNDANT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_RENDUNDANCY_DETAIL: ~0 rows (approximately)
DELETE FROM `OI_RENDUNDANCY_DETAIL`;
/*!40000 ALTER TABLE `OI_RENDUNDANCY_DETAIL` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_RENDUNDANCY_DETAIL` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_RENDUNDANCY_STATE
CREATE TABLE IF NOT EXISTS `OI_RENDUNDANCY_STATE` (
  `RENDUNDANT_ID` int(11) NOT NULL,
  `RENDUNDANTNAME` varchar(20) DEFAULT NULL,
  `DESCRIPTION` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`RENDUNDANT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_RENDUNDANCY_STATE: ~0 rows (approximately)
DELETE FROM `OI_RENDUNDANCY_STATE`;
/*!40000 ALTER TABLE `OI_RENDUNDANCY_STATE` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_RENDUNDANCY_STATE` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_SCREEN_LIST
CREATE TABLE IF NOT EXISTS `OI_SCREEN_LIST` (
  `ID_SCREEN` int(11) NOT NULL,
  `ID_LOGIN` int(11) DEFAULT NULL,
  `ID_FRAME` int(11) DEFAULT NULL,
  `SCREENNAME` varchar(200) DEFAULT NULL,
  `SCREENTYPE` varchar(20) DEFAULT NULL,
  `BACKGROUND_COLOR` varchar(20) DEFAULT NULL,
  `BACKGROUND_IMAGE` varchar(20) DEFAULT NULL,
  `WIDTH` int(11) DEFAULT NULL,
  `HEIGHT` int(11) DEFAULT NULL,
  `TOP` int(11) DEFAULT NULL,
  `BUTTOM` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_SCREEN`),
  KEY `FK_OI_SCREE_REFERENCE_OI_FRAME` (`ID_FRAME`),
  KEY `FK_OI_SCREE_SCREENTOL_OI_LOGIN` (`ID_LOGIN`),
  CONSTRAINT `FK_OI_SCREE_REFERENCE_OI_FRAME` FOREIGN KEY (`ID_FRAME`) REFERENCES `OI_FRAME_LIST` (`ID_FRAME`),
  CONSTRAINT `FK_OI_SCREE_SCREENTOL_OI_LOGIN` FOREIGN KEY (`ID_LOGIN`) REFERENCES `OI_LOGIN_SYSTEM` (`ID_LOGIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_SCREEN_LIST: ~0 rows (approximately)
DELETE FROM `OI_SCREEN_LIST`;
/*!40000 ALTER TABLE `OI_SCREEN_LIST` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_SCREEN_LIST` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_SCRIPT
CREATE TABLE IF NOT EXISTS `OI_SCRIPT` (
  `ID_SCRIPT` int(11) NOT NULL,
  `SCRIPTNAME` varchar(200) DEFAULT NULL,
  `DRESCRIPTION` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID_SCRIPT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_SCRIPT: ~0 rows (approximately)
DELETE FROM `OI_SCRIPT`;
/*!40000 ALTER TABLE `OI_SCRIPT` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_SCRIPT` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_SCRIPT_CONFIGURATION
CREATE TABLE IF NOT EXISTS `OI_SCRIPT_CONFIGURATION` (
  `ID_SCRIPT_CONFIG` int(11) NOT NULL,
  `ID_FUNCTION` int(11) DEFAULT NULL,
  `ID_SCRIPT` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_SCRIPT_CONFIG`),
  KEY `FK_OI_SCRIP_REFERENCE_OI_FUNCT` (`ID_FUNCTION`),
  KEY `FK_OI_SCRIP_REFERENCE_OI_SCRIP` (`ID_SCRIPT`),
  CONSTRAINT `FK_OI_SCRIP_REFERENCE_OI_FUNCT` FOREIGN KEY (`ID_FUNCTION`) REFERENCES `OI_FUNCTION_LIST` (`ID_FUNCTION`),
  CONSTRAINT `FK_OI_SCRIP_REFERENCE_OI_SCRIP` FOREIGN KEY (`ID_SCRIPT`) REFERENCES `OI_SCRIPT` (`ID_SCRIPT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_SCRIPT_CONFIGURATION: ~0 rows (approximately)
DELETE FROM `OI_SCRIPT_CONFIGURATION`;
/*!40000 ALTER TABLE `OI_SCRIPT_CONFIGURATION` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_SCRIPT_CONFIGURATION` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_SYMBOL
CREATE TABLE IF NOT EXISTS `OI_SYMBOL` (
  `ID_SYMBOL` int(11) NOT NULL,
  `SYMBOLNAME` varchar(100) DEFAULT NULL,
  `PATH` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID_SYMBOL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_SYMBOL: ~0 rows (approximately)
DELETE FROM `OI_SYMBOL`;
/*!40000 ALTER TABLE `OI_SYMBOL` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_SYMBOL` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_TIMER
CREATE TABLE IF NOT EXISTS `OI_TIMER` (
  `ID_TIMER_LIST` int(11) NOT NULL,
  `ID_FUNCTION` int(11) DEFAULT NULL,
  `INPUTVARIABLE` int(11) DEFAULT NULL,
  `OUTPUTVARIABLE` int(11) DEFAULT NULL,
  `TIMERNAME` varchar(200) DEFAULT NULL,
  `TIMERTYPE` varchar(10) DEFAULT NULL,
  `ACCUMULATOR` int(11) DEFAULT NULL,
  `PRESET` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_TIMER_LIST`),
  KEY `FK_OI_TIMER_REFERENCE_OI_FUNCT` (`ID_FUNCTION`),
  KEY `FK_OI_TIMER_REFERENCE_OI_PROCE` (`OUTPUTVARIABLE`),
  CONSTRAINT `FK_OI_TIMER_REFERENCE_OI_FUNCT` FOREIGN KEY (`ID_FUNCTION`) REFERENCES `OI_FUNCTION_LIST` (`ID_FUNCTION`),
  CONSTRAINT `FK_OI_TIMER_REFERENCE_OI_PROCE` FOREIGN KEY (`OUTPUTVARIABLE`) REFERENCES `OI_PROCESS_VARIABLE` (`ID_VARIABLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_TIMER: ~0 rows (approximately)
DELETE FROM `OI_TIMER`;
/*!40000 ALTER TABLE `OI_TIMER` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_TIMER` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_USER_AUTH_DETAIL
CREATE TABLE IF NOT EXISTS `OI_USER_AUTH_DETAIL` (
  `ID_DETAIL` int(11) NOT NULL,
  `ID_LOGIN` int(11) NOT NULL,
  `AUTHLEVEL` int(11) DEFAULT NULL,
  `READCONTENT` tinyint(1) DEFAULT NULL,
  `WRITECONTENT` tinyint(1) DEFAULT NULL,
  `EXPORTCONTENT` tinyint(1) DEFAULT NULL,
  `IMPORTCONTENT` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ID_DETAIL`),
  UNIQUE KEY `AK_ID_LOGIN_FK` (`ID_LOGIN`),
  CONSTRAINT `FK_OI_USER__AUTHDETAI_OI_LOGIN` FOREIGN KEY (`ID_LOGIN`) REFERENCES `OI_LOGIN_SYSTEM` (`ID_LOGIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_USER_AUTH_DETAIL: ~0 rows (approximately)
DELETE FROM `OI_USER_AUTH_DETAIL`;
/*!40000 ALTER TABLE `OI_USER_AUTH_DETAIL` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_USER_AUTH_DETAIL` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_VARIABLE_TYPE
CREATE TABLE IF NOT EXISTS `OI_VARIABLE_TYPE` (
  `ID_VARIABLE_TYPE` int(11) NOT NULL,
  `NAME` varchar(100) DEFAULT NULL,
  `CODE` char(3) DEFAULT NULL,
  PRIMARY KEY (`ID_VARIABLE_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_VARIABLE_TYPE: ~0 rows (approximately)
DELETE FROM `OI_VARIABLE_TYPE`;
/*!40000 ALTER TABLE `OI_VARIABLE_TYPE` DISABLE KEYS */;
/*!40000 ALTER TABLE `OI_VARIABLE_TYPE` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
