-- --------------------------------------------------------
-- Host:                         192.168.1.196
-- Server version:               10.1.48-MariaDB-0+deb9u2 - Debian 9.13
-- Server OS:                    debian-linux-gnu
-- HeidiSQL Version:             11.3.0.6295
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for db_oi
CREATE DATABASE IF NOT EXISTS `db_oi` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `db_oi`;

-- Dumping structure for table db_oi.OI_ALARM_GROUP
CREATE TABLE IF NOT EXISTS `OI_ALARM_GROUP` (
  `ID_GROUP` int(11) NOT NULL,
  `GROUPNAME` varchar(20) DEFAULT NULL,
  `DESCRIPTION` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_GROUP`),
  UNIQUE KEY `INDEX_1` (`ID_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_ALARM_GROUP: ~2 rows (approximately)
DELETE FROM `OI_ALARM_GROUP`;
/*!40000 ALTER TABLE `OI_ALARM_GROUP` DISABLE KEYS */;
INSERT INTO `OI_ALARM_GROUP` (`ID_GROUP`, `GROUPNAME`, `DESCRIPTION`) VALUES
	(1, 'Normal', 'XXXXX'),
	(2, 'Critial', 'XXXXX');
/*!40000 ALTER TABLE `OI_ALARM_GROUP` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_EVENT_LIST
CREATE TABLE IF NOT EXISTS `OI_EVENT_LIST` (
  `ID_ALARM` int(11) NOT NULL,
  `ID_GROUP` int(11) DEFAULT NULL,
  `ALARMNAME` varchar(20) DEFAULT NULL,
  `PRIORITY` varchar(10) DEFAULT NULL,
  `DESCRIPTION` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_ALARM`),
  KEY `FK_OI_EVENT_EVENTLIST_OI_ALARM` (`ID_GROUP`),
  CONSTRAINT `FK_OI_EVENT_EVENTLIST_OI_ALARM` FOREIGN KEY (`ID_GROUP`) REFERENCES `OI_ALARM_GROUP` (`ID_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_EVENT_LIST: ~3 rows (approximately)
DELETE FROM `OI_EVENT_LIST`;
/*!40000 ALTER TABLE `OI_EVENT_LIST` DISABLE KEYS */;
INSERT INTO `OI_EVENT_LIST` (`ID_ALARM`, `ID_GROUP`, `ALARMNAME`, `PRIORITY`, `DESCRIPTION`) VALUES
	(1, 1, 'TESALARM1', 'Low', 'XXXXX'),
	(2, 1, 'TESALARM2', 'Mid', 'XXXXX'),
	(3, 1, 'TESALARM3', 'High', 'XXXXX');
/*!40000 ALTER TABLE `OI_EVENT_LIST` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_EVENT_LOG
CREATE TABLE IF NOT EXISTS `OI_EVENT_LOG` (
  `ID_LOG` int(11) NOT NULL,
  `ID_ALARM` int(11) DEFAULT NULL,
  `ID_VARIABLE` int(11) DEFAULT NULL,
  `DATETIME` datetime DEFAULT NULL,
  `VALUE` varchar(100) DEFAULT NULL,
  `DESCRIPTION` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_LOG`),
  KEY `FK_OI_EVENT_EVENTLOGT_OI_PROCE` (`ID_VARIABLE`),
  KEY `FK_OI_EVENT_EVENTLOGT_OI_EVENT` (`ID_ALARM`),
  CONSTRAINT `FK_OI_EVENT_EVENTLOGT_OI_EVENT` FOREIGN KEY (`ID_ALARM`) REFERENCES `OI_EVENT_LIST` (`ID_ALARM`),
  CONSTRAINT `FK_OI_EVENT_EVENTLOGT_OI_PROCE` FOREIGN KEY (`ID_VARIABLE`) REFERENCES `OI_PROCESS_VARIABLE` (`ID_VARIABLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_EVENT_LOG: ~1 rows (approximately)
DELETE FROM `OI_EVENT_LOG`;
/*!40000 ALTER TABLE `OI_EVENT_LOG` DISABLE KEYS */;
INSERT INTO `OI_EVENT_LOG` (`ID_LOG`, `ID_ALARM`, `ID_VARIABLE`, `DATETIME`, `VALUE`, `DESCRIPTION`) VALUES
	(1, 2, 1, '2021-07-15 00:38:38', '0', 'XXXXX');
/*!40000 ALTER TABLE `OI_EVENT_LOG` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_FUNCTION_CATEGORY
CREATE TABLE IF NOT EXISTS `OI_FUNCTION_CATEGORY` (
  `ID_CATEGORY` int(11) NOT NULL,
  `CATEGORYNAME` varchar(20) DEFAULT NULL,
  `DESCRIPTION` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_CATEGORY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_FUNCTION_CATEGORY: ~2 rows (approximately)
DELETE FROM `OI_FUNCTION_CATEGORY`;
/*!40000 ALTER TABLE `OI_FUNCTION_CATEGORY` DISABLE KEYS */;
INSERT INTO `OI_FUNCTION_CATEGORY` (`ID_CATEGORY`, `CATEGORYNAME`, `DESCRIPTION`) VALUES
	(1, 'Runtime', 'XXXXX'),
	(2, 'OS', 'XXXXX');
/*!40000 ALTER TABLE `OI_FUNCTION_CATEGORY` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_FUNCTION_LIST
CREATE TABLE IF NOT EXISTS `OI_FUNCTION_LIST` (
  `ID_FUNCTION` int(11) NOT NULL,
  `ID_CATEGORY` int(11) DEFAULT NULL,
  `FUNCTIONTYPE` varchar(50) DEFAULT NULL,
  `FUNCTIONNAME` varchar(100) DEFAULT NULL,
  `DESCRIPTION` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_FUNCTION`),
  KEY `FK_OI_FUNCT_FUNCTIONT_OI_FUNCT` (`ID_CATEGORY`),
  CONSTRAINT `FK_OI_FUNCT_FUNCTIONT_OI_FUNCT` FOREIGN KEY (`ID_CATEGORY`) REFERENCES `OI_FUNCTION_CATEGORY` (`ID_CATEGORY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_FUNCTION_LIST: ~3 rows (approximately)
DELETE FROM `OI_FUNCTION_LIST`;
/*!40000 ALTER TABLE `OI_FUNCTION_LIST` DISABLE KEYS */;
INSERT INTO `OI_FUNCTION_LIST` (`ID_FUNCTION`, `ID_CATEGORY`, `FUNCTIONTYPE`, `FUNCTIONNAME`, `DESCRIPTION`) VALUES
	(1, 1, 'Application', 'OI_Restart_Runtime', 'XXXXX'),
	(2, 2, 'OS', 'OI_Restart_PC', 'XXXXX'),
	(3, 2, 'OS', 'OI_Shutdown_PC', 'XXXXX');
/*!40000 ALTER TABLE `OI_FUNCTION_LIST` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_LOGIN_SYSTEM
CREATE TABLE IF NOT EXISTS `OI_LOGIN_SYSTEM` (
  `ID_LOGIN` int(11) NOT NULL,
  `FIRSTNAME` varchar(25) DEFAULT NULL,
  `LASTNAME` varchar(25) DEFAULT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  `USERNAME` varchar(100) DEFAULT NULL,
  `LASTLOGIN` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_LOGIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Table untuk login session';

-- Dumping data for table db_oi.OI_LOGIN_SYSTEM: ~1 rows (approximately)
DELETE FROM `OI_LOGIN_SYSTEM`;
/*!40000 ALTER TABLE `OI_LOGIN_SYSTEM` DISABLE KEYS */;
INSERT INTO `OI_LOGIN_SYSTEM` (`ID_LOGIN`, `FIRSTNAME`, `LASTNAME`, `PASSWORD`, `USERNAME`, `LASTLOGIN`) VALUES
	(1, 'Admin', 'AdminOI', '123456', 'admin', '2021-07-15 00:19:40');
/*!40000 ALTER TABLE `OI_LOGIN_SYSTEM` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_MASTER_DRIVER
CREATE TABLE IF NOT EXISTS `OI_MASTER_DRIVER` (
  `ID_DRIVER` int(11) NOT NULL,
  `DRIVERNAME` varchar(50) DEFAULT NULL,
  `ISENABLED` tinyint(1) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID_DRIVER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_MASTER_DRIVER: ~1 rows (approximately)
DELETE FROM `OI_MASTER_DRIVER`;
/*!40000 ALTER TABLE `OI_MASTER_DRIVER` DISABLE KEYS */;
INSERT INTO `OI_MASTER_DRIVER` (`ID_DRIVER`, `DRIVERNAME`, `ISENABLED`, `DESCRIPTION`) VALUES
	(1, 'OPCUA', 1, 'OPCUA CLIENT DRIVER');
/*!40000 ALTER TABLE `OI_MASTER_DRIVER` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_MASTER_DRIVER_CONFIGURATION
CREATE TABLE IF NOT EXISTS `OI_MASTER_DRIVER_CONFIGURATION` (
  `ID_CONFIGURATION` int(11) NOT NULL,
  `ID_DRIVER` int(11) DEFAULT NULL,
  `CONFIGNAME` varchar(100) DEFAULT NULL,
  `VALUE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_CONFIGURATION`),
  KEY `INDEX_1` (`ID_CONFIGURATION`),
  KEY `FK_OI_MASTE_CONFIGDRI_OI_MASTE` (`ID_DRIVER`),
  CONSTRAINT `FK_OI_MASTE_CONFIGDRI_OI_MASTE` FOREIGN KEY (`ID_DRIVER`) REFERENCES `OI_MASTER_DRIVER` (`ID_DRIVER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_MASTER_DRIVER_CONFIGURATION: ~3 rows (approximately)
DELETE FROM `OI_MASTER_DRIVER_CONFIGURATION`;
/*!40000 ALTER TABLE `OI_MASTER_DRIVER_CONFIGURATION` DISABLE KEYS */;
INSERT INTO `OI_MASTER_DRIVER_CONFIGURATION` (`ID_CONFIGURATION`, `ID_DRIVER`, `CONFIGNAME`, `VALUE`) VALUES
	(1, 1, 'IPAddr', '192.168.1.1'),
	(2, 1, 'Port', '4040'),
	(3, 1, 'Url', 'http:/opc.SiLVueOI');
/*!40000 ALTER TABLE `OI_MASTER_DRIVER_CONFIGURATION` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_OBJECT_LIST
CREATE TABLE IF NOT EXISTS `OI_OBJECT_LIST` (
  `OBJECT_ID` int(11) NOT NULL,
  `ID_SCREEN` int(11) DEFAULT NULL,
  `ID_FUNCTION` int(11) DEFAULT NULL,
  `ID_VARIABLE` int(11) DEFAULT NULL,
  `OBJECTNAME` varchar(50) DEFAULT NULL,
  `OBJECTTYPE` varchar(50) DEFAULT NULL,
  `LAYER` int(11) DEFAULT NULL,
  `POS_X` int(11) DEFAULT NULL,
  `POS_Y` int(11) DEFAULT NULL,
  `WIDTH` int(11) DEFAULT NULL,
  `HEIGHT` int(11) DEFAULT NULL,
  `ROTATION` int(11) DEFAULT NULL,
  `IMAGE` varchar(20) DEFAULT NULL,
  `TEXT` varchar(100) DEFAULT NULL,
  `OBJECT_COLOR` varchar(10) DEFAULT NULL,
  `VISIBILITY` tinyint(1) DEFAULT NULL,
  `TRANSPARANCY` int(11) DEFAULT NULL,
  `FLASHING` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`OBJECT_ID`),
  UNIQUE KEY `INDEX_1` (`OBJECT_ID`),
  KEY `FK_OI_OBJEC_REFERENCE_OI_SCREE` (`ID_SCREEN`),
  KEY `FK_OI_OBJEC_REFERENCE_OI_FUNCT` (`ID_FUNCTION`),
  KEY `FK_OI_OBJEC_REFERENCE_OI_PROCE` (`ID_VARIABLE`),
  CONSTRAINT `FK_OI_OBJEC_REFERENCE_OI_FUNCT` FOREIGN KEY (`ID_FUNCTION`) REFERENCES `OI_FUNCTION_LIST` (`ID_FUNCTION`),
  CONSTRAINT `FK_OI_OBJEC_REFERENCE_OI_PROCE` FOREIGN KEY (`ID_VARIABLE`) REFERENCES `OI_PROCESS_VARIABLE` (`ID_VARIABLE`),
  CONSTRAINT `FK_OI_OBJEC_REFERENCE_OI_SCREE` FOREIGN KEY (`ID_SCREEN`) REFERENCES `OI_SCREEN_LIST` (`ID_SCREEN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_OBJECT_LIST: ~0 rows (approximately)
DELETE FROM `OI_OBJECT_LIST`;
/*!40000 ALTER TABLE `OI_OBJECT_LIST` DISABLE KEYS */;
INSERT INTO `OI_OBJECT_LIST` (`OBJECT_ID`, `ID_SCREEN`, `ID_FUNCTION`, `ID_VARIABLE`, `OBJECTNAME`, `OBJECTTYPE`, `LAYER`, `POS_X`, `POS_Y`, `WIDTH`, `HEIGHT`, `ROTATION`, `IMAGE`, `TEXT`, `OBJECT_COLOR`, `VISIBILITY`, `TRANSPARANCY`, `FLASHING`) VALUES
	(1, 1, 1, 1, 'OI_BTN_SUBMIT', 'BUTTON', 1, 1231, 2323, 200, 100, 1, 'src/home/debian/xxxx', 'SUBMIT', '#FFFFF', 0, 100, 1);
/*!40000 ALTER TABLE `OI_OBJECT_LIST` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_PROCESS_VARIABLE
CREATE TABLE IF NOT EXISTS `OI_PROCESS_VARIABLE` (
  `ID_VARIABLE` int(11) NOT NULL,
  `ID_DRIVER` int(11) DEFAULT NULL,
  `VARIABLENAME` varchar(100) DEFAULT NULL,
  `VARIABLETYPE` varchar(20) DEFAULT NULL,
  `DEFAULTVALUE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID_VARIABLE`),
  KEY `FK_OI_PROCE_DRIVERPRO_OI_MASTE` (`ID_DRIVER`),
  CONSTRAINT `FK_OI_PROCE_DRIVERPRO_OI_MASTE` FOREIGN KEY (`ID_DRIVER`) REFERENCES `OI_MASTER_DRIVER` (`ID_DRIVER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_PROCESS_VARIABLE: ~3 rows (approximately)
DELETE FROM `OI_PROCESS_VARIABLE`;
/*!40000 ALTER TABLE `OI_PROCESS_VARIABLE` DISABLE KEYS */;
INSERT INTO `OI_PROCESS_VARIABLE` (`ID_VARIABLE`, `ID_DRIVER`, `VARIABLENAME`, `VARIABLETYPE`, `DEFAULTVALUE`) VALUES
	(1, 1, 'TES1', 'BOOL', '0'),
	(2, 1, 'TES2', 'BOOL', '0'),
	(3, 1, 'TES3', 'INT', '0');
/*!40000 ALTER TABLE `OI_PROCESS_VARIABLE` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_RENDUNDANCY_DETAIL
CREATE TABLE IF NOT EXISTS `OI_RENDUNDANCY_DETAIL` (
  `DETAIL_ID` int(11) NOT NULL,
  `RENDUNDANT_ID` int(11) NOT NULL,
  `CONFIGNAME` varchar(50) DEFAULT NULL,
  `VALUE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`DETAIL_ID`),
  KEY `FK_OI_RENDU_RENDUNDAN_OI_RENDU` (`RENDUNDANT_ID`),
  CONSTRAINT `FK_OI_RENDU_RENDUNDAN_OI_RENDU` FOREIGN KEY (`RENDUNDANT_ID`) REFERENCES `OI_RENDUNDANCY_STATE` (`RENDUNDANT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_RENDUNDANCY_DETAIL: ~4 rows (approximately)
DELETE FROM `OI_RENDUNDANCY_DETAIL`;
/*!40000 ALTER TABLE `OI_RENDUNDANCY_DETAIL` DISABLE KEYS */;
INSERT INTO `OI_RENDUNDANCY_DETAIL` (`DETAIL_ID`, `RENDUNDANT_ID`, `CONFIGNAME`, `VALUE`) VALUES
	(1, 1, 'OI_D_IPaddr', '192.168.1.1'),
	(2, 1, 'OI_D_IPAddrSecondary', '192.168.1.2'),
	(3, 2, 'OI_ND_IPaddr', '192.168.10'),
	(4, 2, 'OI_ND_IPAddrSecondary', '192.168.11');
/*!40000 ALTER TABLE `OI_RENDUNDANCY_DETAIL` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_RENDUNDANCY_STATE
CREATE TABLE IF NOT EXISTS `OI_RENDUNDANCY_STATE` (
  `RENDUNDANT_ID` int(11) NOT NULL,
  `RENDUNDANTNAME` varchar(20) DEFAULT NULL,
  `DESCRIPTION` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`RENDUNDANT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_RENDUNDANCY_STATE: ~2 rows (approximately)
DELETE FROM `OI_RENDUNDANCY_STATE`;
/*!40000 ALTER TABLE `OI_RENDUNDANCY_STATE` DISABLE KEYS */;
INSERT INTO `OI_RENDUNDANCY_STATE` (`RENDUNDANT_ID`, `RENDUNDANTNAME`, `DESCRIPTION`) VALUES
	(1, 'Dominant', 'Dominant Rendundancy'),
	(2, 'Non-Dominant', 'Non Dominant Rendundancy');
/*!40000 ALTER TABLE `OI_RENDUNDANCY_STATE` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_SCREEN_LIST
CREATE TABLE IF NOT EXISTS `OI_SCREEN_LIST` (
  `ID_SCREEN` int(11) NOT NULL,
  `ID_LOGIN` int(11) DEFAULT NULL,
  `SCREENNAME` varchar(200) DEFAULT NULL,
  `SCREENTYPE` varchar(20) DEFAULT NULL,
  `BACKGROUND_COLOR` varchar(20) DEFAULT NULL,
  `BACKGROUND_IMAGE` varchar(20) DEFAULT NULL,
  `WIDTH` int(11) DEFAULT NULL,
  `HEIGHT` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_SCREEN`),
  KEY `FK_OI_SCREE_REFERENCE_OI_LOGIN` (`ID_LOGIN`),
  CONSTRAINT `FK_OI_SCREE_REFERENCE_OI_LOGIN` FOREIGN KEY (`ID_LOGIN`) REFERENCES `OI_LOGIN_SYSTEM` (`ID_LOGIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_SCREEN_LIST: ~1 rows (approximately)
DELETE FROM `OI_SCREEN_LIST`;
/*!40000 ALTER TABLE `OI_SCREEN_LIST` DISABLE KEYS */;
INSERT INTO `OI_SCREEN_LIST` (`ID_SCREEN`, `ID_LOGIN`, `SCREENNAME`, `SCREENTYPE`, `BACKGROUND_COLOR`, `BACKGROUND_IMAGE`, `WIDTH`, `HEIGHT`) VALUES
	(1, 1, 'Main', 'Login', '#FFFFA', 'Src/home/debian/xxxx', 1920, 1080);
/*!40000 ALTER TABLE `OI_SCREEN_LIST` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_SYMBOL_LIBRARY
CREATE TABLE IF NOT EXISTS `OI_SYMBOL_LIBRARY` (
  `ID_SYMBOL` int(11) NOT NULL,
  `ID_SCREEN` int(11) DEFAULT NULL,
  `ELEMENTNAME` varchar(20) DEFAULT NULL,
  `IMAGE` varchar(20) DEFAULT NULL,
  `CATEGORY` varchar(20) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID_SYMBOL`),
  KEY `FK_OI_SYMBO_SYMBOLLIB_OI_SCREE` (`ID_SCREEN`),
  CONSTRAINT `FK_OI_SYMBO_SYMBOLLIB_OI_SCREE` FOREIGN KEY (`ID_SCREEN`) REFERENCES `OI_SCREEN_LIST` (`ID_SCREEN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_SYMBOL_LIBRARY: ~1 rows (approximately)
DELETE FROM `OI_SYMBOL_LIBRARY`;
/*!40000 ALTER TABLE `OI_SYMBOL_LIBRARY` DISABLE KEYS */;
INSERT INTO `OI_SYMBOL_LIBRARY` (`ID_SYMBOL`, `ID_SCREEN`, `ELEMENTNAME`, `IMAGE`, `CATEGORY`, `DESCRIPTION`) VALUES
	(1, 1, 'IMG1', 'src/home/debian/xxx', 'Symbol', 'List symbol');
/*!40000 ALTER TABLE `OI_SYMBOL_LIBRARY` ENABLE KEYS */;

-- Dumping structure for table db_oi.OI_USER_AUTH_DETAIL
CREATE TABLE IF NOT EXISTS `OI_USER_AUTH_DETAIL` (
  `DETAIL_ID` int(11) NOT NULL,
  `ID_LOGIN` int(11) NOT NULL,
  `AUTHLEVEL` int(11) DEFAULT NULL,
  `READCONTENT` tinyint(1) DEFAULT NULL,
  `WRITECONTENT` tinyint(1) DEFAULT NULL,
  `EXPORTCONTENT` tinyint(1) DEFAULT NULL,
  `IMPORTCONTENT` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`DETAIL_ID`),
  UNIQUE KEY `AK_ID_LOGIN_FK` (`ID_LOGIN`),
  CONSTRAINT `FK_OI_USER__AUTHDETAI_OI_LOGIN` FOREIGN KEY (`ID_LOGIN`) REFERENCES `OI_LOGIN_SYSTEM` (`ID_LOGIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_oi.OI_USER_AUTH_DETAIL: ~1 rows (approximately)
DELETE FROM `OI_USER_AUTH_DETAIL`;
/*!40000 ALTER TABLE `OI_USER_AUTH_DETAIL` DISABLE KEYS */;
INSERT INTO `OI_USER_AUTH_DETAIL` (`DETAIL_ID`, `ID_LOGIN`, `AUTHLEVEL`, `READCONTENT`, `WRITECONTENT`, `EXPORTCONTENT`, `IMPORTCONTENT`) VALUES
	(1, 1, 1, 1, 1, 1, 1);
/*!40000 ALTER TABLE `OI_USER_AUTH_DETAIL` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
